version: '3.7'
services:
  backend:
    build: 
      context: backend
      dockerfile: Dockerfile
    ports: 
      - "5175:5175"

  frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile
    volumes: 
      - "./frontend:/app/"
    depends_on: 
      - backend
    ports: 
      - "8080:80"
