version: '3.7'
services:
    
  backend:
    build: 
      context: backend
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
    networks: 
      - integration

  frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile
    command: nodemon start frontend/app.js
    volumes: 
      - "./frontend:/app/"
    depends_on: 
      - backend
    ports: 
      - "3000:3000"
